### ISSUE TITLE
documentation should be explicit about the custom exception constructor contract

### ISSUE THREAD

**Issue by joelmarty** [OpenFeign/feign-annotation-error-decoder#8]
Documentation about custom exception de-serialization - using deserialized error response bodies - does not state anything about its contract:
```java
class ComplexPojoException extends Exception {

    @FeignExceptionConstructor
    public ComplexPojoException(GithubExceptionResponse body) {

    }
}
```
it should be documented that at setup-time, feign will test the exception generators using a null body and that such a test should appear in the constructor:
```java
class ComplexPojoException extends Exception {

    @FeignExceptionConstructor
    public ComplexPojoException(GithubExceptionResponse body) {
        if (body != null) {
            // extract data
        } else {
            // fallback code
        }
    }
}
```

**Comment by saintf** [comment]
done :)

**Comment by hellboy81** [comment]
in which cases I can get null in body?

```java
if (body != null) {
            // extract data
```

**Comment by saintf** [comment]
@hellboy81 in 2 cases:

1. If there is actually no body in the response (even with an error code). This can (and in many different API's, has) happened
1. on startup, the exception generators try to test out that it can actually create exceptions. For those Exceptions that have a body, it basically sends null (since this is meant to be a valid value) to validate the constructor works. This was thought of in terms of fail-fast.
